from .user import User
from .department import Department
from .lab import Lab
from .class_model import Class
from .timeslot import TimeSlot
from .timetable import WeeklyTimetable
from .booking import Booking
from .notification import Notification
from .holiday import Holiday
